Improved the entry point of the documentation.
ocaml-community/yojson pull request #128
Opened 2022-01-27 10:41 UTC by panglesd

This PR adds an `index.mld` to improve the entry point of the documentation.

It allows to:
- Hide packages that we do not want to include in the doc (such as `yojson-bench`)
- Describe the library in a short page, without the details of the API.

I think that it solves #112 and #44.

2022-01-27 11:01 UTC, Leonidas-from-XIV requested changes
I think it is nice. While I am aware that most of it is just moving documentation around, I think some of it should be updated to not state things that aren't the case anymore.

2022-01-27 11:01 UTC, Leonidas-from-XIV commented on lib/yojson.cppo.mli
> +   - The {{!raw}Raw} JSON type, a superset of JSON, safer but less integrated with ocaml types.
```suggestion
   - The {{!raw}Raw} JSON type, a superset of JSON, safer but less integrated with OCaml types.
```

2022-01-27 12:31 UTC, panglesd commented
I added a mention that one of the goal of yojson is to eventually support the json5 standard... I think that's a reasonable goal to have but I can remove this line if you prefer, as no work has started on this feature!

2022-01-27 16:48 UTC, Leonidas-from-XIV commented
@panglesd I have made a proposal in #106 and started an experimental implementation but I am not sure there is a consensus on it yet. I'd suggest we first decide what to do with that RFC :-)

2022-01-31 14:06 UTC, panglesd commented
Sure! I removed the json5 mention and implemented your comments.
We'll discuss json5 in #105.

2022-01-31 16:24 UTC, Leonidas-from-XIV approved these changes

2022-01-31 19:39 UTC, merged