improve pretty printing
ocaml-community/yojson pull request #141
Opened 2022-06-03 15:57 UTC by c-cube

cf #140

2022-06-03 16:04 UTC, Leonidas-from-XIV requested changes
Already much better not to have so many dangling opening parens. I'll fix the changelog on `master`.

2022-06-03 16:04 UTC, Leonidas-from-XIV commented on lib/pretty.ml
> +let rec format inbox std (out:Format.formatter) (x:t) : unit =
Can you change this to `in_box`? I can't get my mind to not read it as "inbox".

2022-06-03 16:04 UTC, Leonidas-from-XIV commented on CHANGES.md
> +- Fix pretty-printing behavior for lists/objects inside lists
This should actually go into a new `unreleased` section, I'll push this on `master`.

2022-06-03 16:49 UTC, Leonidas-from-XIV commented on CHANGES.md
> +- Fix pretty-printing behavior for lists/objects inside lists
```suggestion
- Fix pretty-printing behavior for lists/objects inside lists (#141, @c-cube)
```

2022-06-03 17:01 UTC, merged

2022-06-06 22:46 UTC, mjambon commented
Don't you want to reserve wrapping (hov box) for only sequences of "atoms" (null, boolean, number, string, `{}`, `[]`) like it was done before, and print the rest either horizontally or vertically (hv box)? This requires inspecting the list of items to determine the formatting style but it's lightweight. Please let me know if a PR would help.

2022-06-07 01:12 UTC, c-cube commented
Ah, that's interesting. I didn't realize it was done this way, but it makes sense (hv box for big objects is nicer). I think it can wait but that's just my personal opinion, and if you want to make a PR it'll make @Leonidas-from-XIV happy :)

2022-06-07 03:15 UTC, mjambon commented
@c-cube ok, the PR is in! #142